### ISSUE TITLE
[BUG]Uncaught Error: Class 'App\Constants\ErrorCode' not found

### ISSUE THREAD

**Issue by ZhengSheng1992** [kumaomao/validate#2]
class ValidateException extends ServerException
{
    public function __construct(int $code = 0, string $message = null, Throwable $previous = null)
    {
//        if (is_null($message)) {
//            $message = ErrorCode::getMessage($code);
//        }
        parent::__construct($message, $code, $previous);
    }
}
Kumaomao\Validate\Exception\ValidateException .php这个文件use App\Constants\ErrorCode;
项目默认是没有这个文件的
每次安装都要修改这个才行

**Comment by kumaomao** [comment]
这个问题我应该是修复过，你composer最新的看下

**Comment by ZhengSheng1992** [comment]
https://packagist.org/packages/kumaomao/validate 这里1.1.1还是没有

**Comment by kumaomao** [comment]
对不起，应该是改了没更新，现在更新了。1.1.2没有ErrorCode这个了
